--Friendlist for Azzy AI
--Automatically generated by Azzy AI.
--To add friends, put mercenary or homun into standby mode (ctl+T or alt+T as appropriate), and sit 1 cell to the west (to left in default view) of the person who you wish to friend
--To remove friends, put merc/homun into standby mode, and sit 1 cell to the east (to right in default view) of the person you want to remove.
--
--To add KOS/Enemy/Etc lists, get the ID number from ROPD or by friending them, and make a line like
--MyFriends{2322797}=KOS
--Possible values are NEUTRAL, KOS (kill on sight), ENEMY (assume hostile, but don't attack), and ALLY (assume friendly).
MyFriends={}
MyFriends[110015026]=1 -- 
MyFriends[2226443]=1 -- 
MyFriends[2222204]=1 -- 
MyFriends[2222913]=1 -- 
MyFriends[110015107]=1 -- 
MyFriends[2000231]=1 -- 
MyFriends[2223488]=1 -- 
MyFriends[2000348]=1 -- 
MyFriends[112327742]=1 -- 
MyFriends[-109924283]=1 -- 
MyFriends[2222493]=1 -- 
MyFriends[110113026]=1 -- 
MyFriends[110015847]=1 -- 
MyFriends[114360341]=1 -- 
MyFriends[116193067]=1 -- 
MyFriends[110007736]=1 -- 
MyFriends[2000893]=1 -- 
MyFriends[2225176]=1 -- 
MyFriends[2225051]=1 -- 
MyFriends[1529417]=1 -- 
MyFriends[115122755]=1 -- 
MyFriends[2222580]=1 -- 
MyFriends[2223739]=1 -- 
MyFriends[110401120]=1 -- 
MyFriends[115625525]=1 -- 
MyFriends[2223453]=1 -- 
MyFriends[2226950]=1 -- 
MyFriends[2224390]=1 -- 
MyFriends[110810576]=1 -- 
MyFriends[110015135]=1 -- 
MyFriends[2000849]=1 -- 
